[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit PN532@^1.2.0
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    me-no-dev/ESP Async TCP@^1.1.4
    esphoekma/Preferences@^2.0.0